__include__: [
  '../../psod/deim/DEIM/configs/dfine/dfine_hgnetv2_n_custom.yml'
]

output_dir: outputs/nwpu_vhr10_new_box_fullscale

num_classes: 10
remap_mscoco_category: False

epoches: 120
flat_epoch: 60
no_aug_epoch: 15
lr_gamma: 0.1

train_dataloader:
  total_batch_size: 16
  num_workers: 4
  dataset:
    type: CocoDetection
    img_folder: /home/pc/gxy/Point-DEIM/dataset/nwpu_vhr10/images/train
    ann_file: /home/pc/gxy/PSOD/train_pseudo.json
    transforms:
      policy:
        epoch: 112
  collate_fn:
    stop_epoch: 112

val_dataloader:
  total_batch_size: 8
  num_workers: 4
  dataset:
    type: CocoDetection
    img_folder: /home/pc/gxy/Point-DEIM/dataset/nwpu_vhr10/images/val
    ann_file: /home/pc/gxy/Point-DEIM/dataset/nwpu_vhr10/annotations/instances_val.json
